default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: server_development
  host: db

test:
  <<: *default
  database: server_test
  host: db

production:
  <<: *default
  database: server_production
  username: server
  password: <%= ENV['SERVER_DATABASE_PASSWORD'] %>
