default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  database: server_development
  host: db

test:
  <<: *default
  database: server_test
  host: <%= ENV["DB_HOST"] %>
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: server_production
  username: <%= ENV["MYSQL_USER_NAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
