# frozen_string_literal: true

require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/rbenv"
require "capistrano/bundler"
require "capistrano/rails/migrations"

Dir.glob("lib/capistrano/tasks/*.rb").each { |r| import r }
