# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.5"

gem "active_model_serializers"
gem "bcrypt"
gem "bootsnap", ">= 1.4.2", require: false
gem "devise-i18n"
gem "devise_token_auth"
gem "mysql2", ">= 0.4.4"
gem "oauth2"
gem "omniauth"
gem "omniauth-github"
gem "omniauth-google-oauth2"
gem "omniauth-twitter"
gem "puma", "~> 4.1"
gem "rack-cors"
gem "rails", "~> 6.0.1"
gem "rails-i18n"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "rspec-rails"
end

group :development do
  gem "better_errors"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "pry-byebug"
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :production do
  gem "unicorn"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
